/*
 * Simples Hello
 * teste
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contato@autbank.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.micronaut.example.api;

import com.example.micronaut.example.model.Teste;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import jakarta.annotation.Generated;

@Controller
public interface DefaultApi {

    @Get("/hello")
    Teste hello();
}