openapi: 3.0.1

info:
  title: Simples Hello
  description: "Any Example"
  version: 0.0.1

servers:
  - url: /

paths:
  /hello:
    get:
      summary: oi
      description: Manda um oi ao usuário e o mostra links úteis
      operationId: hello
      responses:
        200:
          description: Movimento incluido com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teste'

components:
  schemas:
    LastRetryRecurringPaymentIds:
      type: array
      example:
        - Any Example
      items:
        type: string
        example:
          - TXpRMU9UQTROMWhZV2xSU1FUazJSMDl
    Teste:
      type: object
      properties:
        array:
          type: array
          items:
            type: string
            example:
              - Any Example
        array2:
          type: array
          items:
            type: string
            example:
              - Any Example
              - Other Example
        array3:
          type: array
          items:
            $ref: '#/components/schemas/LastRetryRecurringPaymentIds'
